In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dulieuxettuyendaihoc.csv')

In [3]:
print("--- 10 DÒNG ĐẦU TIÊN CỦA TẬP DỮ LIỆU ---")
display(df.head(10))

--- 10 DÒNG ĐẦU TIÊN CỦA TẬP DỮ LIỆU ---

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

In [4]:
print("\n--- 10 DÒNG CUỐI CÙNG CỦA TẬP DỮ LIỆU ---")
display(df.tail(10))

--- 10 DÒNG CUỐI CÙNG CỦA TẬP DỮ LIỆU ---

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
90,91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,...,8.3,8.7,7.8,M,NaN,2,6.25,4.00,6.50,A
91,92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,...,7.2,7.4,7.0,M,NaN,2NT,4.75,4.75,4.50,A
92,93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,...,5.9,6.7,5.8,M,NaN,1,3.25,5.25,4.25,A
93,94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,...,8.7,7.8,5.0,M,NaN,1,3.50,4.25,5.00,A
94,95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,...,7.3,6.8,5.3,M,NaN,1,4.25,2.50,4.75,A
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,NaN,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,NaN,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,NaN,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,NaN,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,NaN,2NT,5.25,2.50,4.25,C

In [10]:
print("--- KHẢO SÁT DỮ LIỆU THIẾU CỘT DÂN TỘC (DT) ---")
# Lập bảng tần số và tần suất (bao gồm cả giá trị thiếu NaN)
dt_tanso = df['DT'].value_counts(dropna=False)
dt_tansuất = df['DT'].value_counts(dropna=False, normalize=True) * 100

print("Bảng tần số cột DT:\n", dt_tanso)
print("\nBảng tần suất (%) cột DT:\n", dt_tansuất)
print("\nCác giá trị riêng biệt (Unique) trong cột DT:", df['DT'].unique())

# Thay thế các giá trị bị thiếu bằng giá trị 0 (Dùng phép gán chuẩn mới)
df['DT'] = df['DT'].fillna(0)
print("\n-> Kết quả: Đã xử lý thiếu cột DT bằng cách điền giá trị 0.")

--- KHẢO SÁT DỮ LIỆU THIẾU CỘT DÂN TỘC (DT) ---
Bảng tần số cột DT:
 DT
0.0    97
1.0     2
6.0     1
Name: count, dtype: int64

Bảng tần suất (%) cột DT:
 DT
0.0    97.0
1.0     2.0
6.0     1.0
Name: proportion, dtype: float64

Các giá trị riêng biệt (Unique) trong cột DT: [0. 1. 6.]

-> Kết quả: Đã xử lý thiếu cột DT bằng cách điền giá trị 0.

In [11]:
print("--- KHẢO SÁT DỮ LIỆU THIẾU BIẾN T1 ---")
# Tính giá trị trung bình (Mean) của cột T1
t1_mean = df['T1'].mean()
print(f"Giá trị trung bình (Mean) của cột T1 là: {t1_mean:.2f}")

# Thay thế dữ liệu thiếu bằng giá trị Mean (Dùng phép gán chuẩn mới)
df['T1'] = df['T1'].fillna(t1_mean)
print("-> Kết quả: Đã xử lý thiếu cột T1 bằng phương pháp Mean.")

--- KHẢO SÁT DỮ LIỆU THIẾU BIẾN T1 ---
Giá trị trung bình (Mean) của cột T1 là: 5.95
-> Kết quả: Đã xử lý thiếu cột T1 bằng phương pháp Mean.

In [12]:
# Tạo danh sách tất cả các cột điểm số học tập lớp 10, 11, 12 và điểm thi đại học
cac_cot_diem = []
for nam in ['1', '2', '6']:
    for mon in ['T', 'L', 'H', 'S', 'V', 'X', 'D', 'N']:
        cac_cot_diem.append(f"{mon}{nam}")
cac_cot_diem.extend(['DH1', 'DH2', 'DH3'])

# Dùng vòng lặp quét qua và điền Mean (Dùng phép gán chuẩn mới)
for cot in cac_cot_diem:
    if df[cot].isnull().sum() > 0:
        mean_val = df[cot].mean()
        df[cot] = df[cot].fillna(mean_val)
        
print("-> Kết quả: Đã tự động xử lý toàn bộ dữ liệu điểm số còn thiếu bằng phương pháp Mean.")

-> Kết quả: Đã tự động xử lý toàn bộ dữ liệu điểm số còn thiếu bằng phương pháp Mean.

In [13]:
# Công thức: TBM = (T*2 + L + H + S + V*2 + X + D + N) / 10
df['TBM1'] = (df['T1']*2 + df['L1'] + df['H1'] + df['S1'] + df['V1']*2 + df['X1'] + df['D1'] + df['N1']) / 10
df['TBM2'] = (df['T2']*2 + df['L2'] + df['H2'] + df['S2'] + df['V2']*2 + df['X2'] + df['D2'] + df['N2']) / 10
df['TBM3'] = (df['T6']*2 + df['L6'] + df['H6'] + df['S6'] + df['V6']*2 + df['X6'] + df['D6'] + df['N6']) / 10

print("-> Kết quả: Đã tạo xong các biến trung bình môn TBM1, TBM2, TBM3.")
display(df[['TBM1', 'TBM2', 'TBM3']].head())

-> Kết quả: Đã tạo xong các biến trung bình môn TBM1, TBM2, TBM3.

   TBM1  TBM2  TBM3
0  7.00  7.54  7.01
1  4.69  5.47  5.07
2  5.77  5.38  6.04
3  6.21  5.20  6.88
4  6.50  6.36  6.99

In [14]:
def dinh_dang_xep_loai(tbm):
    if tbm < 5.0: return 'Y'
    elif tbm < 6.5: return 'TB'
    elif tbm < 8.0: return 'K'
    elif tbm < 9.0: return 'G'
    else: return 'XS'

df['XL1'] = df['TBM1'].apply(dinh_dang_xep_loai)
df['XL2'] = df['TBM2'].apply(dinh_dang_xep_loai)
df['XL3'] = df['TBM3'].apply(dinh_dang_xep_loai)

print("-> Kết quả: Đã xếp loại học lực xong (XL1, XL2, XL3).")
display(df[['TBM1', 'XL1', 'TBM2', 'XL2', 'TBM3', 'XL3']].head())

-> Kết quả: Đã xếp loại học lực xong (XL1, XL2, XL3).

   TBM1 XL1  TBM2 XL2  TBM3 XL3
0  7.00   K  7.54   K  7.01   K
1  4.69   Y  5.47  TB  5.07  TB
2  5.77  TB  5.38  TB  6.04  TB
3  6.21  TB  5.20  TB  6.88   K
4  6.50   K  6.36  TB  6.99   K

In [15]:
# Chuẩn hóa quy đổi tuyến tính hệ 10 sang hệ 4: US_TBM = (TBM / 10) * 4
df['US_TBM1'] = (df['TBM1'] / 10) * 4
df['US_TBM2'] = (df['TBM2'] / 10) * 4
df['US_TBM3'] = (df['TBM3'] / 10) * 4

print("-> Kết quả: Đã chuyển đổi điểm sang hệ 4 Mỹ (US_TBM1, US_TBM2, US_TBM3).")
display(df[['TBM1', 'US_TBM1', 'TBM2', 'US_TBM2', 'TBM3', 'US_TBM3']].head())

-> Kết quả: Đã chuyển đổi điểm sang hệ 4 Mỹ (US_TBM1, US_TBM2, US_TBM3).

   TBM1  US_TBM1  TBM2  US_TBM2  TBM3  US_TBM3
0  7.00    2.800  7.54    3.016  7.01    2.804
1  4.69    1.876  5.47    2.188  5.07    2.028
2  5.77    2.308  5.38    2.152  6.04    2.416
3  6.21    2.484  5.20    2.080  6.88    2.752
4  6.50    2.600  6.36    2.544  6.99    2.796

In [16]:
def tinh_ket_qua_xet_tuyen(row):
    khoi_thi = row['KT']
    dh1 = row['DH1']
    dh2 = row['DH2']
    dh3 = row['DH3']
    
    if khoi_thi in ['A', 'A1']:
        diem_xet_tuyen = (dh1 * 2 + dh2 + dh3) / 4
    elif khoi_thi == 'B':
        diem_xet_tuyen = (dh1 + dh2 * 2 + dh3) / 4
    else:
        diem_xet_tuyen = (dh1 + dh2 + dh3) / 3
        
    return 1 if diem_xet_tuyen >= 5.0 else 0

df['KQXT'] = df.apply(tinh_ket_qua_xet_tuyen, axis=1)

print("--- THỐNG KÊ KẾT QUẢ XÉT TUYỂN (1: ĐẬU, 0: RỚT) ---")
print(df['KQXT'].value_counts())

--- THỐNG KÊ KẾT QUẢ XÉT TUYỂN (1: ĐẬU, 0: RỚT) ---
KQXT
0    88
1    12
Name: count, dtype: int64

In [17]:
df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)
print("[THÀNH CÔNG] Đã lưu file sạch tại thư mục hiện hành với tên: processed_dulieuxettuyendaihoc.csv")

[THÀNH CÔNG] Đã lưu file sạch tại thư mục hiện hành với tên: processed_dulieuxettuyendaihoc.csv